# Generated by Django 4.2 on 2023-06-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_aboutus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='title',
        ),
    ]
